# Generated by Django 5.1 on 2025-10-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mentorshiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='seeker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seeker_photos/'),
        ),
    ]
