# Generated by Django 5.1 on 2025-10-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seeker_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='blog_images/'),
        ),
    ]
