# Generated by Django 5.1 on 2025-10-12 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.blogpost')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_blog_posts', to='core.seeker')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('seeker', 'blog')},
            },
        ),
    ]
