# Generated by Django 5.1 on 2025-10-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_savedblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedblog',
            name='is_saved',
            field=models.BooleanField(default=True),
        ),
    ]
