# Generated by Django 5.1 on 2025-10-12 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_savedblog_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedblog',
            name='is_saved',
        ),
    ]
