# Generated by Django 5.1 on 2025-10-13 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_savedblog_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiree',
            name='avilabilty',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='retiree',
            name='skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, null=True, size=None),
        ),
    ]
