# Generated by Django 5.1 on 2025-10-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_retiree_avilabilty_retiree_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiree',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma separated list of skills', null=True),
        ),
    ]
