# Generated by Django 5.1 on 2025-10-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='retiree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.retiree'),
        ),
        migrations.AddField(
            model_name='savedblog',
            name='retiree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_blog_posts', to='core.retiree'),
        ),
        migrations.AlterField(
            model_name='savedblog',
            name='seeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_blog_posts', to='core.seeker'),
        ),
    ]
