# Generated by Django 5.1 on 2025-10-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_blogcomment_retiree_savedblog_retiree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='retiree',
        ),
        migrations.RemoveField(
            model_name='savedblog',
            name='retiree',
        ),
        migrations.CreateModel(
            name='RetireeBlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Retireecomments', to='core.blogpost')),
                ('retiree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.retiree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seeker')),
            ],
        ),
        migrations.CreateModel(
            name='RetireeSavedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiree_saved_by', to='core.blogpost')),
                ('retiree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiree_saved_blog_posts', to='core.retiree')),
                ('seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retiree_saved_blog_posts', to='core.seeker')),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('seeker', 'blog')},
            },
        ),
    ]
