# Generated by Django 5.1 on 2025-10-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_blogcomment_retiree_remove_savedblog_retiree_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retireeblogcomment',
            name='user',
        ),
    ]
