# Generated by Django 5.1 on 2025-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_report_reporter_report_reporter_retiree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiree',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Approved by Admin'),
        ),
    ]
