from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import * 
urlpatterns = [
path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('about/',about, name='about'),
    path('contact/',contact, name='contact'), 
    path('Faq/',Faq, name='Faq'),
    path('RRegistration/',RRegistration, name='RRegistration'),
    path('Rlogin/',Rlogin, name='Rlogin'),
    path("Rlogout/",Rlogout, name="Rlogout"),
    path("Slogout/",Slogout, name="Slogout"),
    path("Rdashboard/",Rdashboard, name="Rdashboard"),
    path("SRegistration/",SRegistration,name='SRegistration'),
    path("Slogin/",Slogin,name='Slogin'),
    path("Sdashboard/",Sdashboard, name="Sdashboard"),
    path("mentors_browsing/",mentors_browsing, name="mentors_browsing"),
    path("vieweachretireeprofile/<int:mentor_id>",vieweachretireeprofile, name="vieweachretireeprofile"),
    path('mentor/blog/<int:blog_id>/', view_mentor_blog, name='view_mentor_blog'),
    path("follow/<int:mentor_id>/",follow_mentor, name="follow_mentor"),
    path("follow-requests/",follow_requests, name="follow_requests"),
    path("accept-request/<int:req_id>/",accept_request, name="accept_request"),
    path("reject-request/<int:req_id>/",reject_request, name="reject_request"),
    path("mentor_dashboardprofile/", mentor_dashboardprofile, name="mentor_dashboardprofile"),
    path("edit_bio/", edit_mentor_profile, name="edit_mentor_profile"),
    path("change_photo/",change_profile_photo, name="change_profile_photo"),
    path("add_blog/<int:mentor_id>/",add_blog, name="add_blog"),
    path("send_mentorship_request/<int:mentorid>/", send_mentorship_request, name="send_mentorship_request"),
    path('unsend_request/<int:request_id>/',unsend_mentorship_request, name='unsend_request'),
    path("mentorship_requests/", mentorship_requests, name="mentorship_requests"),
    path("respond_mentorship_request/<int:req_id>/<str:action>/", respond_mentorship_request, name="respond_mentorship_request"),
    path("seeker_mentorship_requests/", seeker_mentorship_requests, name="seeker_mentorship_requests"),
    path("seeker_dashboardprofile/", seeker_dashboardprofile, name="seeker_dashboardprofile"),
    path("edit_seeker_goals/", edit_seeker_goals, name="edit_seeker_goals"),
    path("edit_seeker_interests/", edit_seeker_interests, name="edit_seeker_interests"),
    path("change_seeker_photo/", change_seeker_photo, name="change_seeker_photo"),
    path('seeker/blogs/',seeker_blog_feed, name='seeker_blog_feed'),
    path('blog/<slug:slug>/',view_blog, name='view_blog'),
    path('like_blog/<int:blog_id>/', like_blog, name='like_blog'),
    path('save_blog/<int:blog_id>/', save_blog, name='save_blog'),
    path('add_comment/<int:blog_id>/', add_comment, name='add_comment'),
    path('chat/<int:mentor_id>/',chat, name='chat'),
    path('retiree/chat/<int:seeker_id>/',retiree_chat, name='retiree_chat'),
    path('retiree/chats/', retiree_chat_inbox, name='retiree_chat_inbox'),
    path('retiree/blogs/',retiree_blog_feed, name='retiree_blog_feed'),
    path('retiree/blogs/like/<int:blog_id>/',retiree_like_blog, name='retiree_like_blog'),
    path('retiree/blogs/save/<int:blog_id>/',retiree_save_blog, name='retiree_save_blog'),
    path('retiree/blogs/comment/<int:blog_id>/',retiree_add_comment, name='retiree_add_comment'),
    path('retiree/blogs/<int:blog_id>/',retiree_blog_detail, name='retiree_blog_detail'),
    path('blogs/',public_blog_list, name='public_blog_list'),
    path('blog/<slug:slug>/', public_blog_detail, name='public_blog_detail'),
    path('blogs/search/',public_blog_search, name='public_blog_search'),
    path('admin_login/', admin_login, name='admin_login'),
    path('admin_logout/', admin_logout, name='admin_logout'),
    path('admin-dashboard/', admin_dashboard, name='admin_dashboard'),
    path('admin-blog-action/<int:blog_id>/<str:action>/', admin_blog_action, name='admin_blog_action'),
    path('admin_user_management/', admin_user_management, name='admin_user_management'),
    path('admin/users/retirees/', retiree_list, name='retiree_list'),
    path('admin/users/seekers/', seeker_list, name='seeker_list'),
    path('delete_retiree/<int:retiree_id>',delete_retiree, name='delete_retiree'),
    path('delete_seeker/<int:seeker_id>', delete_seeker, name='delete_seeker'),
    path('admin_blog_management/', admin_blog_management, name='admin_blog_management'),  
    path('admin-blogs/<int:blog_id>/<str:action>/', admin_deleteblog_action, name='admin_deleteblog_action'),
    path('admin/blogs/<int:blog_id>/', admin_blog_detail, name='admin_blog_detail'),
    path('admin_mentorship_management/', admin_mentorship_management, name='admin_mentorship_management'),
    path('admin_delete_mentorship/<int:request_id>/', admin_mentorship_action, name='admin_mentorship_action'),
    path('admin_report_management/', admin_report_management, name='admin_report_management'),
    path('admin/report-action/<int:report_id>/<str:action>/', admin_report_action, name='admin_report_action'),
    path('admin/report-detail/<int:report_id>/', admin_report_detail, name='admin_report_detail'),
    path('submit-report/', submit_report, name='submit_report'),
    path('admin_mentor_approval/', admin_mentor_approval, name='admin_mentor_approval'),
    ]